services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - NUM_WORKERS=4
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.6'
    #       memory: 140M
    networks:
      - rdb
      - payment-processor
    depends_on:
      - redis

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - NUM_WORKERS=4
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.6'
    #       memory: 140M
    networks:
      - rdb
      - payment-processor
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.1'
    #       memory: 30M
    networks:
      - rdb
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.2'
    #       memory: 40M
    networks:
      - rdb

networks:
  rdb:
    driver: bridge
  payment-processor:
    external: true

