services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback
    networks:
      - rdb
      - payment-processor
    depends_on:
      - postgres
      - redis

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback
    networks:
      - rdb
      - payment-processor
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8888:8888"
    networks:
      - rdb
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rdb
    networks:
      - rdb
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - rdb

networks:
  rdb:
    driver: bridge
  payment-processor:
    external: true

volumes:
  db_data:

