services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    networks:
      - rdb
      - payment-processor
    depends_on:
      - postgres
      - redis

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    networks:
      - rdb
      - payment-processor
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    networks:
      - rdb
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rdb
    networks:
      - rdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - rdb

networks:
  rdb:
    driver: bridge
  payment-processor:
    external: true

volumes:
  db_data:

